//! Generate the cross-language golden-vector fixture consumed by the
//! TypeScript approver client tests.
//!
//! Output: `clients/approver-ts/test/fixtures/preimage_golden.json`.
//!
//! Usage:
//!     cargo run --bin gen-golden-vectors
//!
//! The fixture pins the byte-exact preimage layout produced by
//! `qfc_quorum::SignedApproval::signing_preimage`. The TS client's
//! `preimage.ts` reconstructs the same bytes from the same inputs and
//! the test asserts equality. This means any future change to the
//! Rust-side preimage layout breaks the TS test loudly, forcing a
//! coordinated update.

use std::io::Write;
use std::path::PathBuf;

use qfc_quorum::{ApprovalDecision, SignedApproval};
use qfc_wallet_types::{ApprovalId, RequestId};
use serde::Serialize;
use ulid::Ulid;

#[derive(Serialize)]
struct GoldenVector {
    description: &'static str,
    inputs: GoldenInputs,
    expected_preimage_hex: String,
}

#[derive(Serialize)]
struct GoldenInputs {
    approval_id: String,
    request_id: String,
    message_hash_hex: String,
    decision: &'static str,
    timestamp_unix_ms: i64,
}

#[derive(Serialize)]
struct Fixture {
    note: &'static str,
    vectors: Vec<GoldenVector>,
}

fn main() {
    let approval_id =
        ApprovalId::from_ulid(Ulid::from_string("01J7Z9C5K3MX5W1H7E1D9V4Q2R").unwrap());
    let request_id =
        RequestId::from_ulid(Ulid::from_string("01J7Z9C5K3MX5W1H7E1D9V4Q2S").unwrap());
    let message_hash: [u8; 32] = [0xAB; 32];
    let timestamp_unix_ms: i64 = 1_724_400_000_000;

    let approve = SignedApproval::signing_preimage(
        &approval_id,
        &request_id,
        &message_hash,
        ApprovalDecision::Approve,
        timestamp_unix_ms,
    );
    let reject = SignedApproval::signing_preimage(
        &approval_id,
        &request_id,
        &message_hash,
        ApprovalDecision::Reject,
        timestamp_unix_ms,
    );

    let zero_msg = [0u8; 32];
    let early_ts: i64 = 1;
    let approve_early = SignedApproval::signing_preimage(
        &approval_id,
        &request_id,
        &zero_msg,
        ApprovalDecision::Approve,
        early_ts,
    );

    let fixture = Fixture {
        note: "Generated by tools/gen-golden-vectors. DO NOT EDIT BY HAND. \
               Regenerate via `cargo run --bin gen-golden-vectors`.",
        vectors: vec![
            GoldenVector {
                description: "approve, all-AB message hash, mid-2024 timestamp",
                inputs: GoldenInputs {
                    approval_id: approval_id.to_string(),
                    request_id: request_id.to_string(),
                    message_hash_hex: hex::encode(message_hash),
                    decision: "approve",
                    timestamp_unix_ms,
                },
                expected_preimage_hex: hex::encode(&approve),
            },
            GoldenVector {
                description: "reject, all-AB message hash, mid-2024 timestamp",
                inputs: GoldenInputs {
                    approval_id: approval_id.to_string(),
                    request_id: request_id.to_string(),
                    message_hash_hex: hex::encode(message_hash),
                    decision: "reject",
                    timestamp_unix_ms,
                },
                expected_preimage_hex: hex::encode(&reject),
            },
            GoldenVector {
                description: "approve, zero message hash, timestamp = 1 (BE encoding check)",
                inputs: GoldenInputs {
                    approval_id: approval_id.to_string(),
                    request_id: request_id.to_string(),
                    message_hash_hex: hex::encode(zero_msg),
                    decision: "approve",
                    timestamp_unix_ms: early_ts,
                },
                expected_preimage_hex: hex::encode(&approve_early),
            },
        ],
    };

    let out: PathBuf = std::env::args()
        .nth(1)
        .map(PathBuf::from)
        .unwrap_or_else(|| {
            let manifest = PathBuf::from(env!("CARGO_MANIFEST_DIR"));
            manifest
                .join("..")
                .join("..")
                .join("clients")
                .join("approver-ts")
                .join("test")
                .join("fixtures")
                .join("preimage_golden.json")
        });
    if let Some(parent) = out.parent() {
        std::fs::create_dir_all(parent).unwrap();
    }
    let mut f = std::fs::File::create(&out).unwrap();
    let json = serde_json::to_string_pretty(&fixture).unwrap();
    writeln!(f, "{json}").unwrap();
    eprintln!("wrote {}", out.display());
}
