/**
 * Preimage byte-exact compatibility against the Rust side.
 *
 * Loads `test/fixtures/preimage_golden.json` (generated by
 * `tools/gen-golden-vectors`), reconstructs each vector, and asserts
 * byte equality. If this test breaks, the Rust client's preimage layout
 * changed — regenerate the fixture in lockstep.
 */

import { describe, expect, it } from "vitest";
import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

import {
  buildSigningPreimage,
  bytesToHex,
  hexToBytes,
  PREIMAGE_LEN,
  type Decision,
} from "../src/preimage.js";

interface Fixture {
  note: string;
  vectors: {
    description: string;
    inputs: {
      approval_id: string;
      request_id: string;
      message_hash_hex: string;
      decision: Decision;
      timestamp_unix_ms: number;
    };
    expected_preimage_hex: string;
  }[];
}

const here = dirname(fileURLToPath(import.meta.url));
const fixturePath = join(here, "fixtures", "preimage_golden.json");
const fixture = JSON.parse(readFileSync(fixturePath, "utf8")) as Fixture;

describe("buildSigningPreimage", () => {
  for (const v of fixture.vectors) {
    it(`matches Rust golden vector: ${v.description}`, () => {
      const out = buildSigningPreimage({
        approvalId: v.inputs.approval_id,
        requestId: v.inputs.request_id,
        messageHash: hexToBytes(v.inputs.message_hash_hex),
        decision: v.inputs.decision,
        timestampUnixMs: BigInt(v.inputs.timestamp_unix_ms),
      });
      expect(out.length).toBe(PREIMAGE_LEN);
      expect(bytesToHex(out)).toBe(v.inputs.message_hash_hex === "" ? "" : v.expected_preimage_hex);
    });
  }

  it("rejects wrong-length message hash", () => {
    expect(() =>
      buildSigningPreimage({
        approvalId: "01J7Z9C5K3MX5W1H7E1D9V4Q2R",
        requestId: "01J7Z9C5K3MX5W1H7E1D9V4Q2S",
        messageHash: new Uint8Array(31),
        decision: "approve",
        timestampUnixMs: 0n,
      }),
    ).toThrow(/messageHash/);
  });

  it("rejects wrong-length approval id", () => {
    expect(() =>
      buildSigningPreimage({
        approvalId: "short",
        requestId: "01J7Z9C5K3MX5W1H7E1D9V4Q2S",
        messageHash: new Uint8Array(32),
        decision: "approve",
        timestampUnixMs: 0n,
      }),
    ).toThrow(/approvalId/);
  });

  it("encodes timestamp big-endian i64", () => {
    const out = buildSigningPreimage({
      approvalId: "01J7Z9C5K3MX5W1H7E1D9V4Q2R",
      requestId: "01J7Z9C5K3MX5W1H7E1D9V4Q2S",
      messageHash: new Uint8Array(32),
      decision: "approve",
      timestampUnixMs: 1n,
    });
    const tsTail = out.slice(out.length - 8);
    expect(Array.from(tsTail)).toEqual([0, 0, 0, 0, 0, 0, 0, 1]);
  });
});
